services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime
      POSTGRES_HOST_AUTH_METHOD: trust  # Только для разработки!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      -c autovacuum=on
      -c autovacuum_vacuum_scale_factor=0.1
      -c autovacuum_analyze_scale_factor=0.05
      -c log_temp_files=100MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d realtime -h 127.0.0.1"]
      interval: 2s
      timeout: 2s
      retries: 15

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Важно: с большой буквы!
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/realtime?sslmode=disable&connect_timeout=5&statement_timeout=30000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Важно: с большой буквы!
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: