# Этап сборки
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Сначала копируем только файлы зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем остальные файлы и собираем
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o main .

# Этап запуска
FROM alpine:3.19

# Устанавливаем зависимости для работы с PostgreSQL
RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["./main"]